---
title: "variants"
output: html_document
date: "2024-04-17"
---

```{r}
suppressPackageStartupMessages(library("data.table"))
suppressPackageStartupMessages(library("tidyverse"))
suppressPackageStartupMessages(library("ggplot2"))

####
file_id = 'G_H_507472' # options: ['G_H_507472' 'T_H_50472']
####
# 1. phred encoded site quality (how much confidence have in variant calls)
file = paste('../vcftools/', file_id, '.lqual', sep='')
var_qual = fread(file)
a <- ggplot(var_qual, aes(QUAL)) + geom_density(fill = "dodgerblue1", colour = "black", alpha = 0.3) +
  theme_light()
pdf(paste('../figures/sitequal_', file_id,'.pdf',sep=''))
a
dev.off()

unique(var_qual$QUAL)

# 2. variant mean depth (n reads mapped to each position)
file = paste('../vcftools/', file_id, '.ldepth.mean', sep='')
var_depth = fread(file)
a <- ggplot(var_depth, aes(MEAN_DEPTH)) + geom_density(fill = "dodgerblue1", colour = "black", alpha = 0.3) +
  theme_light()
pdf(paste('../figures/vardepth_', file_id,'.pdf',sep=''))
a
dev.off()

tab = summary(var_depth$MEAN_DEPTH) 
print(tab)
```

```{r}
# gene cts for all
### 
file = '../vcftools/all_genes.frq'
####
df = fread(file) %>% as.data.frame()
df = df %>%
  arrange(CHROM, POS)

# freq of all 
pdf('../figures/gene_freq.pdf')
a = ggplot(df, aes(x=GENE, color=SAMPLE, fill =SAMPLE)) + 
  geom_bar() +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
  ) + 
  labs(title='Gene Frequency (All)', x='Gene', y='Count')
a
dev.off()

# freq of all split by chrom
pdf('../figures/gene_freq_byCHROM.pdf')
a+ facet_grid(CHROM ~ .)
dev.off()


# top only (based on combined occurance in all samples)
###
thres= 4000
###

frq_df = as.data.frame(table(df$GENE) )
colnames(frq_df)= c('GENE', 'Freq')
frq_df = frq_df[order(frq_df$Freq, decreasing = TRUE), ] 
row.names(frq_df)= NULL
# filter based on threshold (occurance)
frq_df = frq_df[frq_df$Freq>thres,]
genes = frq_df$GENE %>% as.vector()

# filter orig dataframe for these genes
s1 = subset(df, GENE %in% genes)

# freq of all 
pdf(paste('../figures/gene_freq_top_',thres,'.pdf',sep=''))
a = ggplot(s1, aes(x=GENE, color=SAMPLE, fill =SAMPLE)) + 
  geom_bar() +
  theme(axis.text.x = element_text(angle = 90))+ 
  labs(title=paste('Top Gene Frequency (>=',thres, ' Freq)',sep=''), x='Gene', y='Count')
a
dev.off()

# freq of all split by chrom
pdf(paste('../figures/gene_freq_byCHROM_top_', thres, '.pdf', sep=''))
a + 
  facet_grid(CHROM ~ .) +
  theme(axis.text.x = element_text(angle = 90))
dev.off()
```















